array_capitulos = [{"numero": 1, "titulo": "El Mandaloriano", "temporada": 1, "precio": 5.99},
    {"numero": 2, "titulo": "El Niño", "temporada": 1, "precio": 5.99},
    {"numero": 3, "titulo": "El Pecado", "temporada": 1, "precio": 5.99},
    { "numero": 4, "titulo": "Santuario", "temporada": 1, "precio": 5.99},
    {"numero": 5, "titulo": "El Pistolero", "temporada": 1, "precio": 5.99},
    {"numero": 6, "titulo": "El Prisionero", "temporada": 1, "precio": 5.99},
    {"numero": 7, "titulo": "El Ajuste de Cuentas", "temporada": 1, "precio": 5.99},
    {"numero": 8, "titulo": "Redención", "temporada": 1, "precio": 5.99},
    {"numero": 9, "titulo": "El Mariscal", "temporada": 2, "precio": 5.99},
    {"numero": 10, "titulo": "La Pasajera", "temporada": 2, "precio": 5.99},
    {"numero": 11, "titulo": "La Heredera", "temporada": 2, "precio": 5.99},
    {"numero": 12, "titulo": "El Asedio", "temporada": 2, "precio": 5.99},
    {"numero": 13, "titulo": "La Jedi", "temporada": 2, "precio": 5.99},
    {"numero": 14, "titulo": "La Tragedia", "temporada": 2, "precio": 5.99},
    {"numero": 15, "titulo": "El Creyente", "temporada": 2, "precio": 5.99},
    {"numero": 16, "titulo": "El Rescate", "temporada": 2, "precio": 5.99},
    {"numero": 17, "titulo": "El Apóstata", "temporada": 3, "precio": 5.99},
    {"numero": 18, "titulo": "Las Minas de Mandalore","temporada": 3, "precio": 5.99},
    {"numero": 19, "titulo": "El Converso", "temporada": 3, "precio": 5.99},
    {"numero": 20, "titulo": "El Huérfano", "temporada": 3, "precio": 5.99},
    {"numero": 21, "titulo": "El Pirata", "temporada": 3, "precio": 5.99},
    {"numero": 22, "titulo": "Pistoleros a Sueldo", "temporada": 3, "precio": 5.99},
    {"numero": 23, "titulo": "Los Espías", "temporada": 3, "precio": 5.99},
    {"numero": 24, "titulo": "El Retorno", "temporada": 3, "precio": 5.99}]
